language: node_js
node_js: 10
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi
before_deploy:
- echo "Deploying!"
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: dev2019
  token:
    secure: "QGCIepB78Cou8kbbLx/sfp0wbk5Qb9zLFBD04DXqpA5GlxHYoTmSK8E9uDz4l+PggRuu4nncdBKJcAV3bE/OeHVxDpcoXZ2IgISYPIBYiS1pWIP9Wtmu3dmYMiVR9/mmiTsXD/oafxBPd+ZhwryqgQbdySaQiQpUfQdJfFnZu576crE3wqFVn2GVp2mUczdseXVyi7fbT79L5KsIp3CPGC+UNFLVBXXxnRqR2W10F8XuQ8wBIE1A635wrhx57irvHK4BbwCSG7Ygmy2E/xalaNzplnU3H90oRQa5dLKdyfPSYD8Xel/SsNa2TcwuBUst1DPOylS06o8RK3BDK9vHGIHr8VDbpXWsg1woWse0Jzoe/aS5glJt5Pbct178c4ZwyfbP4aRZtCeY/2gstBFu3z0NFMXdy00QPS22hklm8EUxabhigTtndMpAZ3G07JTfS1aTt6vh07cTB6P3TBSrWKAzNNlDYMgfPipO6zf8LXnP1XV1yy8EN5lAuvpGat/oZwJrMxtRyj3H0B6Rxg5bo6+/gAYVSASZOQ42CNCuoMwiYC0qyBd1qjF6mUb5BbZRtOAGk4LWSX37fnOlmDWFWDlcaoE2txq6DUumUjJF7IsvpTEXsSNcC7jUyUI+pnmyW5YIyc5ZZcsH7cEwspzxG53ARVvwbT5g3VntJOdC35E="
